FROM quay.io/biocontainers/bwa:0.7.17--hed695b0_7

ARG VERSION=0.7.17

LABEL container.base.image="quay.io/biocontainer/bwa:0.7.17"
LABEL software.name="bwa"
LABEL software.version=${VERSION}
LABEL software.description="Utilities for the Sequence Alignment/Map (SAM/BAM/CRAM) formats"
LABEL software.website="http://www.htslib.org"
LABEL software.documentation="http://www.htslib.org/doc/samtools.html"
LABEL software.license="MIT/Expat"
LABEL tags="Genomics"

ENTRYPOINT ["bwa"]

